apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecommerce  # Nama VirtualService
spec:
  hosts:
    - "*"  # Host yang akan ditangani oleh VirtualService, dalam kasus ini, semuanya ("*")
  gateways:
    - ecommerce-gateway  # Gateway yang akan menggunakan VirtualService ini
  http:
    - match:
        - uri:
            exact: /order  # URI persis "/order"
        - uri:
            prefix: /shipping  # URI dimulai dengan "/shipping"
      route:
        - destination:
            host: order-service  # Mengarahkan ke service "order-service"
            port:
              number: 3000
          weight: 100  # Memberikan bobot 100 (semua traffict menuju order-service)
        - destination:
            host: shipping-service  # Mengarahkan ke service "shipping-service"
            port:
              number: 3001
          weight: 100  # Memberikan bobot 100 (semua traffict menuju shipping-service)
