apiVersion: v1 # Versi API Kubernetes yang digunakan.
kind: PersistentVolume # Jenis objek Kubernetes yang akan dibuat.
metadata:
  labels:
    app: mongodb # Label aplikasi.
    tier: database # Label tier.
  name: mongodb-pv # Nama Persistent Volume (PV).
spec:
  accessModes:
    - ReadWriteOnce # Mode akses PV (dapat dibaca dan ditulis oleh satu node).
  capacity:
    storage: 2Gi # Kapasitas penyimpanan yang dialokasikan untuk PV (2 GiB).
  hostPath:
    path: "/data/db" # Path pada node host tempat PV akan disimpan.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube # PV hanya akan diberikan ke node dengan nama "minikube".
  storageClassName: manual # Nama kelas penyimpanan yang digunakan untuk PV.
---
apiVersion: v1 # Versi API Kubernetes yang digunakan.
kind: PersistentVolumeClaim # Jenis objek Kubernetes yang akan dibuat.
metadata:
  labels:
    app: mongodb # Label aplikasi.
    tier: database # Label tier.
  name: mongodb-pvc # Nama Persistent Volume Claim (PVC).
spec:
  accessModes:
    - ReadWriteOnce # Mode akses PVC (dapat dibaca dan ditulis oleh satu node).
  resources:
    requests:
      storage: 2Gi # Permintaan kapasitas penyimpanan untuk PVC (2 GiB).
  storageClassName: manual # Nama kelas penyimpanan yang diklaim oleh PVC.
