apiVersion: v1 # Versi API Kubernetes yang digunakan.
kind: Service # Jenis objek Kubernetes yang akan dibuat.
metadata:
  name: order-service # Nama Service.
spec:
  selector:
    app: order # Selector pod berdasarkan label app.
  ports:
    - name: http-order
      port: 3000 # Port yang akan digunakan oleh Service.
      protocol: TCP
      targetPort: 3000 # Custom Port pada node host yang akan digunakan oleh Service.
