apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq  # Nama StatefulSet
spec:
  serviceName: rabbitmq  # Nama Service yang akan digunakan oleh StatefulSet
  replicas: 1  # Jumlah replika yang akan dibuat
  selector:
    matchLabels:
      app: rabbitmq  # Seleksi pod berdasarkan label "app: rabbitmq"
  template:
    metadata:
      labels:
        app: rabbitmq  # Label yang akan digunakan untuk pod yang dibuat
    spec:
      containers:
      - name: rabbitmq  # Nama container RabbitMQ
        image: rabbitmq:3.11-management  # Image Docker RabbitMQ yang akan digunakan
        envFrom:
        - configMapRef:
            name: rabbitmq-config  # Menggunakan konfigurasi dari ConfigMap "rabbitmq-config"
        ports:
        - containerPort: 5672  # Port RabbitMQ biasa
        - containerPort: 15672  # Port antarmuka manajemen RabbitMQ
        volumeMounts:
        - name: rabbitmq-data  # Nama volume yang akan digunakan
          mountPath: /var/lib/rabbitmq  # Path tempat data RabbitMQ akan disimpan
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data  # Nama volume claim template
    spec:
      accessModes: ["ReadWriteOnce"]  # Mode akses volume
      resources:
        requests:
          storage: 10Gi  # Permintaan penyimpanan untuk volume claim

