name: CI Pipeline # Nama pipeline.
on:
  push:
    branches:
      - karsajobs # Pipeline akan di trigger (dijalankan) ketika ada push ke branch "karsajobs".
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest # Menentukan runner yang digunakan untuk jobs ini.
    steps:
      - uses: actions/checkout@v3 # Melakukan checkout kode dari repositori.
      - uses: hadolint/hadolint-action@v3.1.0 # Menggunakan action Hadolint untuk melakukan linting Dockerfile.
        with:
          dockerfile: Dockerfile # Menentukan file Dockerfile yang akan dilint.

  test-app:
    runs-on: ubuntu-latest # Menentukan runner yang digunakan untuk jobs ini.
    steps:
      - uses: actions/checkout@v3 # Melakukan checkout kode dari repositori.
      - name: Run unit tests # Memberikan nama untuk step ini.
        run: go test -v -short --count=1 $(go list ./...) # Menjalankan unit tests untuk aplikasi golang (Backend).

  build-app-karsajobs:
    runs-on: ubuntu-latest # Menentukan runner yang digunakan untuk jobs ini.
    steps:
      - uses: actions/checkout@v3 # Melakukan checkout kode dari repositori.
      - name: Build and push Docker Image to Github Packages # Memberikan nama untuk step ini.
        env:
          PASSWORD_DOCKER_HUB: ${{ secrets.PASSWORD_DOCKER_HUB }} # Mengambil password Docker dari secrets.
        run: bash build_push_image_karsajobs.sh # Menjalankan skrip bash untuk build dan push Docker Image ke Github Packages.
